# Generated by Django 4.2 on 2023-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='заголовок ru')),
                ('title_uk', models.CharField(max_length=255, verbose_name='заголовок uk')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='текст ru')),
                ('content_uk', models.TextField(blank=True, null=True, verbose_name='текст uk')),
            ],
            options={
                'verbose_name': 'Текст для страницы',
                'verbose_name_plural': 'Тексты для страниц',
            },
        ),
    ]
