# Generated by Django 4.2 on 2023-04-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPointLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сash point location')),
            ],
            options={
                'verbose_name': 'Локация выдачи наличных',
                'verbose_name_plural': 'Локации выдачи наличных',
            },
        ),
    ]
