# Generated by Django 4.2 on 2023-04-13 15:29

from django.db import migrations
from exchange.models import Currency


def add_names(apps, scheme_editor):
        
    c = Currency(title="btc")
    c.save()

    c = Currency(title="eth")
    c.save()

    c = Currency(title="usd")
    c.save()

    c = Currency(title="uah")
    c.save()



class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_cashpointlocation'),
    ]

    operations = [
            migrations.RunPython(add_names), 
    ]
