# Generated by Django 4.2 on 2023-04-13 16:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0003_auto_20230413_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date of gathering'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='operator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='user_open', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
