# Generated by Django 4.2 on 2023-04-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rate_pub_date_alter_orders_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'выставлен'), ('paid', 'оплачен'), ('canceled', 'отменен')], default='created', max_length=40, verbose_name='Статус')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_currency', to='exchange.currency', verbose_name='Invoice Currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_order', to='exchange.orders', verbose_name='Invoice Order')),
            ],
            options={
                'verbose_name': 'инвойс',
                'verbose_name_plural': 'инвойсы',
            },
        ),
    ]
