# Generated by Django 4.2 on 2023-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('btc', '1231290o3dqwjlsanq0n'), ('eth', 'mgklf9304jhmvlfg8jmrtm')], default='btc', max_length=300, verbose_name='номер кошелька'),
        ),
    ]
