# Generated by Django 4.2 on 2023-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='wallet',
            field=models.CharField(choices=[('1231290o3dqwjlsanq0n', 'btc_wallet'), ('mgklf9304jhmvlfg8jmrtm', 'eth_wallet')], default='btc', max_length=300, verbose_name='номер кошелька'),
        ),
    ]
