# Generated by Django 4.2 on 2023-04-19 06:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0010_alter_invoice_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=32, unique=True, verbose_name='Номер карты')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='wallet',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sum',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40, max_length=255, verbose_name='Сумма инвойса'),
        ),
        migrations.CreateModel(
            name='PoolAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('ext_info', models.CharField(max_length=255, unique=True, verbose_name='Внешний ключ идентификации')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Внешний ключ идентификации или кошелек криптовалюты')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='crypto_payments_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_payments_details', to='exchange.poolaccounts', verbose_name='Crypto Address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiat_payments_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiat_payments_details', to='exchange.fiataccounts', verbose_name='Fiat Card'),
        ),
    ]
