# Generated by Django 4.2 on 2023-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_fiataccounts_remove_invoice_wallet_invoice_sum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiataccounts',
            options={'verbose_name': 'Фиат реквизиты', 'verbose_name_plural': 'Фиат реквизиты'},
        ),
        migrations.AlterModelOptions(
            name='poolaccounts',
            options={'verbose_name': 'Пул криптоадресов', 'verbose_name_plural': 'Пулы криптоадресов'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sum',
            field=models.FloatField(default=0.0, verbose_name='Сумма инвойса'),
        ),
    ]
