# Generated by Django 4.2 on 2023-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_alter_fiataccounts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sum',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40, max_length=255, verbose_name='Сумма инвойса'),
        ),
    ]
