# Generated by Django 4.2 on 2023-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_alter_invoice_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='block_height',
            field=models.IntegerField(default=0, verbose_name='Высота блока'),
        ),
    ]
