# Generated by Django 4.2 on 2023-04-19 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0014_invoice_block_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(editable=False, max_length=255, verbose_name='account ')),
                ('payment_id', models.CharField(editable=False, max_length=255, verbose_name='payment id')),
                ('status', models.CharField(choices=[('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата валидности')),
                ('amnt', models.DecimalField(decimal_places=20, max_digits=40, max_length=255, verbose_name='amnt give')),
                ('txid', models.CharField(blank=True, max_length=255, null=True, verbose_name='crypto txid')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_of_trans', to='exchange.currency', verbose_name='Currency')),
                ('operator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_issued', to=settings.AUTH_USER_MODEL, verbose_name='Опертор')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
