# Generated by Django 4.2 on 2023-04-23 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fiat_payments_details',
        ),
        migrations.AddField(
            model_name='invoice',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата валидности'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'выставлен'), ('paid', 'оплачен'), ('canceled', 'отменен'), ('expired', 'просрочен')], default='created', max_length=40, verbose_name='Статус'),
        ),
    ]
