# Generated by Django 4.2 on 2023-04-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_orders_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='trans',
        ),
    ]
