# Generated by Django 4.2 on 2023-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_orders_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'waiting_checkout'), ('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'waiting_checkout'), ('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='poolaccounts',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'waiting_checkout'), ('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='wait_checkout', max_length=40),
        ),
        migrations.AlterField(
            model_name='trans',
            name='account',
            field=models.CharField(max_length=255, verbose_name='account '),
        ),
        migrations.AlterField(
            model_name='trans',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'waiting_checkout'), ('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
    ]
