# Generated by Django 4.2 on 2023-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_alter_invoice_status_alter_orders_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='debet_credit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дебет/кредит'),
        ),
    ]
