# Generated by Django 4.2 on 2023-04-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_remove_orders_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trans',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_open', to='exchange.trans', verbose_name='транзакция выплаты'),
        ),
    ]
