# Generated by Django 4.2 on 2023-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_opertele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opertele',
            name='tele_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='telegram id'),
        ),
    ]
