# Generated by Django 4.2 on 2023-05-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_alter_opertele_tele_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='cash_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_point', to='exchange.cashpointlocation', verbose_name='Точка выдачи наличных'),
        ),
    ]
