# Generated by Django 4.2 on 2023-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_alter_opertele_tele_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opertele',
            name='tele_link',
            field=models.CharField(max_length=255, null=True, verbose_name='telegram temp link'),
        ),
    ]
