# Generated by Django 4.2 on 2023-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0022_trans_cash_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account '),
        ),
    ]
