# Generated by Django 4.2 on 2023-05-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_trans_secret_key_for_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='secret_key_for_cash',
        ),
    ]
