# Generated by Django 4.2 on 2023-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0025_remove_trans_secret_key_for_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='cash_point',
        ),
        migrations.AlterField(
            model_name='trans',
            name='payment_id',
            field=models.CharField(max_length=255, verbose_name='payment id'),
        ),
    ]
