# Generated by Django 4.2 on 2023-05-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0023_poolaccounts_technical_info_alter_opertele_tele_link'),
        ('exchange', '0026_remove_trans_cash_point_alter_trans_payment_id'),
    ]

    operations = [
    ]
