# Generated by Django 4.2 on 2023-05-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0027_merge_20230504_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolaccounts',
            name='currency_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange.currencyprovider', verbose_name='Сеть'),
        ),
    ]
