# Generated by Django 4.2 on 2023-05-08 11:57

from django.db import migrations
from exchange.models import Currency
from exchange.models import CurrencyProvider


def add_names(apps, scheme_editor):
            
        c = Currency(title="usdt")
        c.save()
        c = CurrencyProvider(title="tron")
        c.save()
        c = CurrencyProvider(title="erc20")
        c.save()
        c = CurrencyProvider(title="native")
        c.save()
        c = CurrencyProvider(title="cashless")
        c.save()
        c = CurrencyProvider(title="cash")
        c.save()



class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0027_merge_20230508_1133'),
    ]

    operations = [
        migrations.RunPython(add_names), 
    ]
