# Generated by Django 4.2 on 2023-05-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_auto_20230508_1157'),
        ('exchange', '0029_trans_currency_provider'),
    ]

    operations = [
    ]
