# Generated by Django 4.2 on 2023-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0030_merge_20230508_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='opertele',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'waiting_checkout'), ('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='opertele',
            name='token',
            field=models.CharField(max_length=255, null=True, verbose_name='telegram k'),
        ),
        migrations.AddField(
            model_name='trans',
            name='aml_check',
            field=models.TextField(default={}, unique=True),
        ),
        migrations.AddField(
            model_name='trans',
            name='tx_raw',
            field=models.TextField(default={}, unique=True),
        ),
        migrations.AlterField(
            model_name='opertele',
            name='tele_link',
            field=models.CharField(max_length=255, null=True, verbose_name='telegram temp link'),
        ),
        migrations.AlterField(
            model_name='trans',
            name='debet_credit',
            field=models.CharField(blank=True, choices=[('in', 'debit'), ('out', 'credit')], max_length=255, null=True, verbose_name='дебет/кредит'),
        ),
    ]
