# Generated by Django 4.2 on 2023-05-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0031_opertele_status_opertele_token_trans_aml_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='aml_check',
            field=models.TextField(default={}),
        ),
        migrations.AlterField(
            model_name='trans',
            name='tx_raw',
            field=models.TextField(default={}),
        ),
    ]
