# Generated by Django 4.2 on 2023-05-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0032_alter_trans_aml_check'),
        ('exchange', '0032_alter_trans_aml_check_alter_trans_tx_raw'),
    ]

    operations = [
    ]
