# Generated by Django 4.2 on 2023-05-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0033_merge_20230509_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitebitDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_currency', models.CharField(max_length=255, verbose_name='Buy Currency')),
                ('sell_currency', models.CharField(max_length=255, verbose_name='Sell Currency')),
            ],
            options={
                'verbose_name': 'Whitebit операция',
                'verbose_name_plural': 'Whitebit операции',
            },
        ),
    ]
