# Generated by Django 4.2 on 2023-05-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0034_whitebitdeals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='trans',
        ),
        migrations.AddField(
            model_name='trans',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_order', to='exchange.orders', verbose_name='Order ID'),
        ),
    ]
