# Generated by Django 4.2 on 2023-05-18 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0035_remove_orders_trans_trans_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trans_order', to='exchange.orders', verbose_name='Order'),
        ),
        migrations.CreateModel(
            name='CheckAml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wait_checkout', 'waiting_checkout'), ('created', 'создана'), ('processing', 'в процессе'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус')),
                ('aml_check', models.TextField(default={})),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_of_trans_check', to='exchange.trans', verbose_name='транса на проверку')),
            ],
        ),
    ]
