# Generated by Django 4.2 on 2023-05-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_alter_trans_order_checkaml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitebitdeals',
            old_name='buy_currency',
            new_name='currency_give',
        ),
        migrations.RenameField(
            model_name='whitebitdeals',
            old_name='sell_currency',
            new_name='currency_take',
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='amnt_give',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, max_length=255, null=True, verbose_name='Сумма продана'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='amnt_take',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, max_length=255, null=True, verbose_name='Сумма получена'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, max_length=255, null=True, verbose_name='Комиссия биржи'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='exchange.orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, max_length=255, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'в процессе'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='processing', max_length=40, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='timestamp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Время выполнения сделки'),
        ),
        migrations.AddField(
            model_name='whitebitdeals',
            name='trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Trans', to='exchange.trans', verbose_name='Trans'),
        ),
    ]
