# Generated by Django 4.2 on 2023-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_alter_trans_order_checkaml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolaccounts',
            name='ext_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний ключ идентификации'),
        ),
    ]
