# Generated by Django 4.2 on 2023-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0037_rename_buy_currency_whitebitdeals_currency_give_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitebitdeals',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='whitebit ID'),
        ),
    ]
