# Generated by Django 4.2 on 2023-05-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0037_alter_poolaccounts_ext_info'),
        ('exchange', '0038_whitebitdeals_client_order_id'),
    ]

    operations = [
    ]
