# Generated by Django 4.2 on 2023-05-23 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0039_merge_20230522_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='operator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_checked', to=settings.AUTH_USER_MODEL, verbose_name='Опертор'),
        ),
        migrations.AlterField(
            model_name='checkaml',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='opertele',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='poolaccounts',
            name='ext_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='доп информации по нативной валюте, если это токен usdt'),
        ),
        migrations.AlterField(
            model_name='poolaccounts',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='wait_checkout', max_length=40),
        ),
        migrations.AlterField(
            model_name='poolaccounts',
            name='technical_info',
            field=models.CharField(default='', max_length=255, verbose_name='Техническая информация для обработки платежей, balance tokena'),
        ),
        migrations.AlterField(
            model_name='trans',
            name='status',
            field=models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='whitebitdeals',
            name='client_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='whitebit ID сделки'),
        ),
        migrations.AlterField(
            model_name='whitebitdeals',
            name='currency_give',
            field=models.CharField(max_length=255, verbose_name='Give Currency'),
        ),
        migrations.AlterField(
            model_name='whitebitdeals',
            name='currency_take',
            field=models.CharField(max_length=255, verbose_name='Take Currency'),
        ),
    ]
