# Generated by Django 4.2 on 2023-05-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0040_invoice_operator_alter_checkaml_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='trans',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='exchange.trans', verbose_name='транзакция выплаты'),
        ),
    ]
