# Generated by Django 4.2 on 2023-05-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0041_orders_trans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trans',
            old_name='debet_credit',
            new_name='debit_credit',
        ),
    ]
