# Generated by Django 4.2 on 2023-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0042_rename_debet_credit_trans_debit_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rate_waved',
            field=models.BooleanField(default=False, verbose_name='Плавающий курс в сделке'),
        ),
    ]
