# Generated by Django 4.2 on 2023-05-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_orders_trans'),
        ('exchange', '0042_rename_debet_credit_trans_debit_credit'),
    ]

    operations = [
    ]
