# Generated by Django 4.2 on 2023-06-11 11:47

from django.db import migrations
from exchange.models import Currency


def add_names(apps, scheme_editor):
    c = Currency(title="eur")
    c.save()

    c = Currency(title="uah безнал")
    c.save()



class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_orders_rate_waved'),
    ]

    operations = [
        migrations.RunPython(add_names),
    ]
