# Generated by Django 4.2 on 2023-06-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_orders_rate_waved'),
    ]

    operations = [
    ]
