# Generated by Django 4.2 on 2023-06-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_orders_rate_waved'),
        ('exchange', '0044_alter_orders_trans'),
    ]

    operations = [
    ]
