# Generated by Django 4.2 on 2023-06-15 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0044_auto_20230611_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid of page for quick connect'),
        ),
    ]
