# Generated by Django 4.2 on 2023-06-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0044_auto_20230611_1147'),
        ('exchange', '0045_merge_0043_orders_rate_waved_0044_alter_orders_trans'),
    ]

    operations = [
    ]
