# Generated by Django 4.2 on 2023-06-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0046_merge_20230611_1208'),
        ('exchange', '0047_auto_20230611_1212'),
    ]

    operations = [
    ]
