# Generated by Django 4.2 on 2023-06-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0045_orders_uuid'),
        ('exchange', '0048_merge_20230611_1213'),
    ]

    operations = [
    ]
