# Generated by Django 4.2 on 2023-04-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rate_pub_date_alter_orders_operator'),
        ('oper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='context_vars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'контекстная перменная',
                'verbose_name_plural': 'контекстные переменные',
            },
        ),
        migrations.CreateModel(
            name='rates_direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(blank=True, default='0')),
                ('give_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_give_wizzard', to='exchange.currency', verbose_name='Give Currency')),
                ('take_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_take_wizzard', to='exchange.currency', verbose_name='Take currency')),
            ],
            options={
                'verbose_name': 'направление обмена',
                'verbose_name_plural': 'направления обменов',
            },
        ),
    ]
