# Generated by Django 4.2 on 2023-04-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0002_context_vars_rates_direction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crypto_trans',
        ),
    ]
