# Generated by Django 4.2 on 2023-04-19 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rate_pub_date_alter_orders_operator'),
        ('oper', '0002_context_vars_rates_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='crypto_trans',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid of page for quick connect'),
        ),
        migrations.AddField(
            model_name='crypto_trans',
            name='account',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='account '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto_trans',
            name='payment_id',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='payment id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='deal',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_issued', to='exchange.orders', verbose_name='заявка'),
        ),
    ]
