# Generated by Django 4.2 on 2023-04-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0003_remove_chat_id_remove_crypto_trans_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crypto_trans',
        ),
    ]
