# Generated by Django 4.2 on 2023-04-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0004_delete_crypto_trans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crypto_trans',
        ),
    ]
