# Generated by Django 4.2 on 2023-05-25 17:35

from django.db import migrations
from exchange.models import Currency
from oper.models import context_vars


def add_risk_context_vars(apps, scheme_editor):
    for i in Currency.objects.all():
        context_vars.objects.create(name="risk"+i.title, value=0.5)


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0005_delete_crypto_trans'),
    ]

    operations = [
        migrations.RunPython(add_risk_context_vars),
    ]
