# Generated by Django 4.2 on 2023-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0006_auto_20230525_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='simple_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('command_params', models.TextField(max_length=255, unique=True, verbose_name='params')),
                ('status', models.CharField(choices=[('wait_checkout', 'ожидает'), ('created', 'создана'), ('processing', 'в процессе'), ('processing2', 'в процессе отправки'), ('wait_secure', 'проверяется'), ('user_canceled', 'отменена клиентом'), ('canceled', 'отменена оператором'), ('processed', 'проведена'), ('failed', 'неуспешна')], default='created', max_length=40, verbose_name='Статус')),
                ('history', models.TextField(default='{}')),
                ('ext_key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Задача на исполнение',
                'verbose_name_plural': 'Задачи на исполнение',
            },
        ),
    ]
