# Generated by Django 4.2 on 2023-05-16 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='public key')),
                ('raw_data', models.TextField(max_length=255, verbose_name='Full info')),
            ],
        ),
    ]
